name: flutter_dropzone_example
description: Demonstrates how to use the flutter_dropzone plugin.

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_dropzone: ^4.2.0
  video_player: ^2.3.0
  http: ^1.2.2
  universal_io: ^2.0.4
  web: ">=0.5.1 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true